openapi: 3.0.1
info:
  title: True Revenue Tax API
  description: |
    When recording in-app revenue, be that IAP or IAS (subscriptions), you are actually reporting gross revenue into the system. Factors such as store commission, tax, or other revenue related elements should be taken into account for each and every transaction.
    True revenue comes to save this heavy lifting for you, so that eventually, all of your revenue metrics will be based on net revenue and calculated accordingly.

  version: 1.0.0
servers:
  - url: http://hq1.appsflyer.com/api/stores-taxes/v1
    description: api server - production
security:
  - bearerAuth: []

paths:
  /update_taxes/app/{app_id}:
    post:
      tags:
        - "Tax rate rules"
      summary: "Create rule"
      parameters:
      - name: app_id
        in: path
        required: true
        schema:
          type: string
        description: "App ID of the app for which you are setting tax rate rule"
        example: id123456789
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxRateRule'
        required: true
      responses:
        200:
          $ref: '#/components/responses/Success'
        400:
          description: Various errors
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  InvalidJson:
                    summary: Invalid json
                    description: Invalid json
                    value:
                      message: "Incorrect JSON format. Please verify and resubmit"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
                  MissingAppId:
                    summary: Missing app_id
                    description: Missing app_id
                    value:
                      message: "integration 0: missing mandatory field 'app_id"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
                  InvalidCountry:
                    summary: invalid country
                    value:
                      message: "Geo (country) code not identified. Please use an ISO 3166-1 alpha 2 (2 letter code)"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
                  SubdivisioPostalNoCountry:
                    summary: Subdivision or Postal code without country
                    description: Subdivision or Postal code without country
                    value:
                      message: "For the returned object, country must be defined"
                  TaxRateAlreadyExists:
                   summary: Tax rate already exists
                   description: Tax rate already exists
                   value:
                     message: "For the returned object, a tax rate already exists"
                  TaxRateMissing:
                   summary: Tax rate missing
                   description: Tax rate missing
                   value:
                     message: "For the returned object, the parameter tax_rate is missing"
                     request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
                  MissingCountry:
                    summary: Missing country
                    description: Missing country
                    value:
                      message: "For the returned object, the parameter country is missing"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
                  TaxNameMissing:
                    summary: Missing tax name
                    description: Missing tax name
                    value:
                      message: "For the returned object, the parameter tax_name is missing"
                  InvalidSourceEvent:
                   summary: invalid source_event
                   description: invalid source_event
                   value:
                     message: "integration 0, appID='com.config_4.test', network='chartboosts2s_int': invalid source event suffix 'something_monetized"
        '401':
          description: Missing authorization token
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  MissingAuthorizationToken:
                    summary: Missing authorization token
                    value:
                      message: "Please contact your CSM for further information"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
        '404':
          description: Token unauthorized
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  TokenUnauthorized:
                    summary: Method not allowed
                    value:
                      message: "Method not allowed"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
        '405':
          description: Method not allowed
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  MethodNotAllowed:
                    summary: Token unauthorized
                    value:
                      message: "Token unauthorized"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
        '429':
          description: Rate limit exceeded
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error' 
                examples:
                  InternalError:
                    summary: Rate limit exceeded
                    value:
                      message: "The rate limit is XXX requests per minute, please try again later"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
        '500':
          description: Internal server error
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error' 
                examples:
                  InternalError:
                    summary: Internal Server Error
                    value:
                      message: "Internal error. please try again later."
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
            

  /get_tax_catalog/app/{app_id}:
    get:
      tags:
        - "Tax rate rules"
      summary: "List integrations"
      parameters:
      - name: app_id
        in: path
        required: true
        schema:
          type: string
        description: "App ID of the app for which you are getting tax rate rule catalog"
        example: id123456789
      responses:
        '200':
          description: Integration returned
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: '#/components/schemas/TaxRateRule'
        '401':
          description: Missing authorization token
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  MissingAuthorizationToken:
                    summary: Missing authorization token
                    value:
                      message: "Please contact your CSM for further information"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
        '404':
          description: Token unauthorized
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  TokenUnauthorized:
                    summary: Method not allowed
                    value:
                      message: "Method not allowed"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
        '405':
          description: Method not allowed
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error'
                examples:
                  MethodNotAllowed:
                    summary: Token unauthorized
                    value:
                      message: "Token unauthorized"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
        '429':
          description: Rate limit exceeded
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error' 
                examples:
                  InternalError:
                    summary: Rate limit exceeded
                    value:
                      message: "The rate limit is XXX requests per minute, please try again later"
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"
        '500':
          description: Internal server error
          content: 
            application/json:
                schema:
                  $ref: '#/components/schemas/Error' 
                examples:
                  InternalError:
                    summary: Internal Server Error
                    value:
                      message: "Internal error. please try again later."
                      request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        To be able to call the API a relevant authorization token should be available for you in AppsFlyer platform (HQ) >> user dropdown (top right corner) >> API tokens >> API token V2.0
  responses:  
    Success:
      description: Valid request
      content: 
        application/json:
            schema:
              type: object
              properties: 
                message:
                  type: string
                request_id:
                  type: string 
              example:
                message: "Successfully processed 1 integration updates"
                request_id: "f1c0af47-bb7a-4e25-a261-d94d07689bb8" 
  schemas:
    Error:
      properties:
        message:
          type: string
        request_id:
          type: string
    TaxRateRule:
      type: object
      required:
        - tax_name
        - tax_rate
      properties:
        tax_name:
          type: string
          description: |
            The *tax_name* appears in the customer’s invoice, and is usually a short name that describes the specific type of tax, such as Sales, VAT, or GST.
          example:
            Sales
        tax_rate:
          type: number
          format: float
          description: |
            The *tax_rate* is a number (up to 4 decimal places) that represents the tax **percentage** to be collected.
          example: 7.25
        tax_exclusive:
          type: boolean
          default: false
          description: |
            The *tax_exclusive* is a boolean parameter. If false, the amount calculated based on the tax_rate included in the overall amount, else, the amount calculated is added to the overall amount.
        country:
          type: string
          minItems: 0
          enum:
            - AF
            - AX
            - AL
            - DZ
            - AS
            - AD
            - AO
            - AI
            - AQ
            - AG
            - AR
            - AM
            - AW
            - AU
            - AT
            - AZ
            - BS
            - BH
            - BD
            - BB
            - BY
            - BE
            - BZ
            - BJ
            - BM
            - BT
            - BO
            - BA
            - BW
            - BV
            - BR
            - IO
            - BN
            - BG
            - BF
            - BI
            - KH
            - CM
            - CA
            - CV
            - KY
            - CF
            - TD
            - CL
            - CN
            - CX
            - CC
            - CO
            - KM
            - CG
            - CD
            - CK
            - CR
            - CI
            - HR
            - CU
            - CY
            - CZ
            - DK
            - DJ
            - DM
            - DO
            - EC
            - EG
            - SV
            - GQ
            - ER
            - EE
            - ET
            - FK
            - FO
            - FJ
            - FI
            - FR
            - GF
            - PF
            - TF
            - GA
            - GM
            - GE
            - DE
            - GH
            - GI
            - GR
            - GL
            - GD
            - GP
            - GU
            - GT
            - GG
            - GN
            - GW
            - GY
            - HT
            - HM
            - VA
            - HN
            - HK
            - HU
            - IS
            - IN
            - ID
            - IR
            - IQ
            - IE
            - IM
            - IL
            - IT
            - JM
            - JP
            - JE
            - JO
            - KZ
            - KE
            - KI
            - KR
            - KP
            - KW
            - KG
            - LA
            - LV
            - LB
            - LS
            - LR
            - LY
            - LI
            - LT
            - LU
            - MO
            - MK
            - MG
            - MW
            - MY
            - MV
            - ML
            - MT
            - MH
            - MQ
            - MR
            - MU
            - YT
            - MX
            - FM
            - MD
            - MC
            - MN
            - ME
            - MS
            - MA
            - MZ
            - MM
            - NA
            - NR
            - NP
            - NL
            - AN
            - NC
            - NZ
            - NI
            - NE
            - NG
            - NU
            - NF
            - MP
            - NO
            - OM
            - PK
            - PW
            - PS
            - PA
            - PG
            - PY
            - PE
            - PH
            - PN
            - PL
            - PT
            - PR
            - QA
            - RE
            - RO
            - RU
            - RW
            - BL
            - SH
            - KN
            - LC
            - MF
            - PM
            - VC
            - WS
            - SM
            - ST
            - SA
            - SN
            - RS
            - SC
            - SL
            - SG
            - SK
            - SI
            - SB
            - SO
            - ZA
            - GS
            - ES
            - LK
            - SD
            - SR
            - SJ
            - SZ
            - SE
            - CH
            - SY
            - TW
            - TJ
            - TZ
            - TH
            - TL
            - TG
            - TK
            - TO
            - TT
            - TN
            - TR
            - TM
            - TC
            - TV
            - UG
            - UA
            - AE
            - GB
            - US
            - UM
            - UY
            - UZ
            - VU
            - VE
            - VN
            - VG
            - VI
            - WF
            - EH
            - YE
            - ZM
            - ZW
          description: |
            Two-letter ISO country code for which the tax is applied
            > ⚠️
            > In case where country, subdivision and postal_code are empty, as well as the remaining parameters are included and valid, the rule will be considered as the default tax rule.
        subdivision:
          type: string
          description: |
            > ⚠️
            > Subdivision is null by default, the granularity of the tax_rate derived from the most granular breakdown available based on the following hierarchy: country | subdivision | postal_code
            > For some countries (for example, the United States) we will report an additional two-letter state. Should be handled according to [SUBDIVISION CODES (ISO 3166-2)](https://service.unece.org/trade/locode/2022-1%20SubdivisionCodes.htm) → expected value format “country_code-subdivision_code”
          example: US-CA
        postal_code:
          type: string
          description: |
            String of numbers and letters that represent groupings of people in geographic areas.
            > ⚠️
            > postal_code is null by default, the granularity of the tax_rate derived from the most granular breakdown available based on the following hierarchy: country | subdivision | postal_code 
          example: "57717"
        deduction_order:
          type: integer
          enum:
            - 0
            - 1
            - 2
          default: 0
          description: |
            The deduction_order is an enum that can be set to one of the following:
            - 0 - store commission is deducted first from the gross revenue and tax is deducted from the amount remaining after store commission
            - 1 - tax is deducted first from the gross and store commission is deducted from the amount remaining after tax
            - 2 - both tax and store commission are deducted from the total revenue







